---
title: "lab_1"
author: "Katherine Rosencrance"
date: "2023-01-13"
output: html_document
---


```{r setup, include=TRUE, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(sf)
library(tmap)
```

### Read in the data and set up
```{r}
sf_trees <- read_csv(here("data", "sf_trees", "sf_trees.csv"))

top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>% 
  slice_max(tree_count, n =5) %>% 
  arrange(-tree_count)

ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count), 
                                y = tree_count))+
  geom_col()+
  labs(y = "Tree count", x = "Legal status")+
  coord_flip()+
  theme_minimal()
```

### Keep observations where legal status is "permitted site" and caretaker is "MTA"
```{r}
permitted_mta <- sf_trees %>% 
  filter(legal_status == 'Permitted Site' & caretaker == 'MTA')
```

### Keep blackwood acacia trees, only legal_status, date, lat, long columns 
```{r}
blackwood_acacia <- sf_trees %>% 
  filter(str_detect(species, "Blackwood Acacia")) %>% 
  select(legal_status, date, latitude, longitude)

### make a plot of sf acacia
ggplot(data= blackwood_acacia, aes(x = longitude, y = latitude))+
  geom_point()

```

### Use tidyr::separate() to separate one column into multiple, and tidyr unite to rejoin

```{r}
sf_trees_sep <- sf_trees %>% 
  separate(species, into = c('spp_scientific', 'spp_common'), sep = ' :: ')

#put two columns together
sf_trees_unite <- sf_trees %>% 
  unite("id_status", tree_id:species, sep = "_NEW_")
```


### Make some actual maps!
```{r}
#sf meaning simple features
blackwood_acacia_sf <- blackwood_acacia %>% 
  drop_na(longitude, latitude) %>% 
st_as_sf(coords = c("longitude", "latitude"))

st_crs(blackwood_acacia_sf) <- 4326

ggplot(data = blackwood_acacia_sf) +
  geom_sf(color = "darkgreen")+
  theme_minimal()
```

### read in sf streets data
```{r}
sf_map_sf <- read_sf(here("data", "sf_map", 'tl_2017_06075_roads.shp')) %>% 
  st_transform (4326)
```

```{r}
ggplot() +
  geom_sf(data = sf_map_sf, size = 0.1, color = "darkgray")+
  geom_sf(data = blackwood_acacia_sf, color = "red", size = 0.5)+
  theme_void()+
  labs(title = "Blackwood acacias in SF")
```

### Interactive map

```{r}
tmap_mode('view')
tm_shape(blackwood_acacia_sf)+
  tm_dots()
```

